### ISSUE TITLE
Support `audit.k8s.io/truncated` label on audit log

### ISSUE THREAD

**Issue by kyasbal** [GoogleCloudPlatform/khi#193]
kube-apiserver audit log can be truncated when it produce a large log for a single request.
It leads KHI to generate misleading timeline. 

When a log is truncated, the audit log should have a label `audit.k8s.io/truncated: "true"`.

example:

```yaml
protoPayload:
    '@type': type.googleapis.com/google.cloud.audit.AuditLog
    authenticationInfo:
        principalEmail: system:serviceaccount:cnrm-system:cnrm-webhook-manager
    authorizationInfo:
        - granted: true
          permission: io.k8s.admissionregistration.v1.mutatingwebhookconfigurations.update
          resource: admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/mutating-webhook.cnrm.cloud.google.com
    methodName: io.k8s.admissionregistration.v1.mutatingwebhookconfigurations.update
    requestMetadata:
        callerIp: 10.0.0.1
        callerSuppliedUserAgent: webhook/v0.0.0 (linux/amd64) kubernetes/$Format
    resourceName: admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/mutating-webhook.cnrm.cloud.google.com
    serviceName: k8s.io
    status:
        code: 0
insertId: foo-bar-qux
resource:
    type: k8s_cluster
    labels:
        project_id: test-project
        location: asia-northeast1
        cluster_name: test-cluster
timestamp: "2025-05-27T04:48:59.261183Z"
labels:
    authorization.k8s.io/reason: 'RBAC: allowed by ClusterRoleBinding "cnrm-webhook-binding" of ClusterRole "cnrm-webhook-role" to ServiceAccount "cnrm-webhook-manager/cnrm-system"'
    audit.k8s.io/truncated: "true"
    authorization.k8s.io/decision: allow
logName: projects/test-project/logs/cloudaudit.googleapis.com%2Factivity
operation:
    id: foo-bar-qux
    producer: k8s.io
    first: true
    last: true
receiveTimestamp: "2025-05-27T04:49:13.171563409Z"
```
